/* Shopping presentation: reuse existing routes, product state, search and delegated controls. */
(() => {
  const svg=path=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${path}</svg>`;
  const gridIcon=svg('<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>');
  const listIcon=svg('<path d="M9 5h12M9 12h12M9 19h12M3 5h1M3 12h1M3 19h1"/>');
  const header=document.querySelector('.masthead'),logo=header.querySelector('.logo'),search=document.querySelector('#searchForm'),phone=document.querySelector('#topPhone'),city=document.querySelector('#cityBtn');
  const cart=header.querySelector('a[href="#/cart"]'),favorite=header.querySelector('a[href="#/favorites"]'),profile=header.querySelector('a[href="#/account"]');
  header.classList.add('shop-header');
  search.querySelector('button[type="submit"]').remove();search.querySelector('input').placeholder='Что вы ищете?';search.insertAdjacentHTML('afterbegin',svg('<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>'));
  const catalog=document.createElement('button');catalog.type='button';catalog.className='shop-catalog';catalog.innerHTML=gridIcon+'<span>Каталог</span>';catalog.setAttribute('aria-label','Каталог');catalog.setAttribute('aria-expanded','false');catalog.setAttribute('aria-controls','shop-catalog-panel');
  const more=document.createElement('button');more.type='button';more.className='shop-icon';more.innerHTML=svg('<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>');more.setAttribute('aria-label','Меню и информация');more.title='Меню и информация';more.setAttribute('aria-expanded','false');more.setAttribute('aria-controls','shop-more-panel');
  for(const [el,label] of [[cart,'Корзина'],[favorite,'Избранное'],[profile,'Личный кабинет']]){el.className='shop-icon';el.setAttribute('aria-label',label);el.title=label;for(const n of [...el.childNodes])if(n.nodeType===3)n.remove();}
  const bar=document.createElement('div');bar.className='shop-bar';const actions=document.createElement('div');actions.className='shop-actions';actions.append(favorite,cart,profile,more);bar.append(logo,catalog,search,phone,actions);phone.hidden=true;const contact=document.createElement('button');contact.type='button';contact.className='shop-icon shop-contact';contact.setAttribute('aria-label','Позвонить в магазин');contact.setAttribute('aria-expanded','false');contact.setAttribute('aria-controls','shop-phone-panel');contact.innerHTML=svg('<path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6 19.8 19.8 0 0 1-3.1-8.7A2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1.9.3 1.8.6 2.6a2 2 0 0 1-.5 2.1L8 9.7a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5c.9.3 1.7.5 2.6.6a2 2 0 0 1 2 2.4Z"/>');actions.prepend(contact);header.replaceChildren(bar);
  document.querySelector('.mainnav').remove();
  const mega=document.createElement('section');mega.id='shop-catalog-panel';mega.className='shop-panel shop-mega';mega.hidden=true;mega.setAttribute('aria-label','Разделы каталога');
  mega.innerHTML=`<div class="shop-panel-head"><h2>Каталог товаров</h2><button type="button" data-shop-close aria-label="Закрыть каталог">×</button></div><div class="shop-categories">${CATS.map(c=>`<a href="#/catalog/${c.id}"><div class="shop-category-visual">${StudioMedia.art(c.id)}</div><span><b>${esc(c.name)}</b><small>${esc(c.note)}</small></span><span aria-hidden="true">↗</span></a>`).join('')}</div><div class="shop-panel-foot"><a class="btn" href="#/catalog">Весь каталог</a><a href="#/brands">Бренды ↗</a><a href="#/promo">Акции ↗</a><a href="#/favorites">Избранное ↗</a></div>`;
  const info=document.createElement('section');info.id='shop-more-panel';info.className='shop-panel shop-info';info.hidden=true;info.setAttribute('aria-label','Информация о магазине');
  info.innerHTML='<div class="shop-panel-head"><h2>Информация</h2><button type="button" data-shop-close aria-label="Закрыть меню">×</button></div><div class="shop-info-links"><a href="#/account">Личный кабинет</a><a href="#/wholesale">Опт и партнёрам</a><a href="#/about">О компании</a><a href="#/contacts">Контакты</a><a href="#/delivery">Доставка и оплата</a><a href="#/returns">Возврат</a><a href="#/offer">Документы и оферта</a><a href="#/privacy">Политика конфиденциальности</a></div><div class="shop-location"><span>Ваш город</span></div>';
  city.hidden=true;info.querySelector('.shop-location').innerHTML='<span>Магазин в Ростове-на-Дону</span><small>ул. Ерёменко, 45</small>';bar.append(city);header.append(mega,info);
  const phones=document.createElement('section');phones.id='shop-phone-panel';phones.className='shop-panel shop-phones';phones.hidden=true;phones.setAttribute('aria-label','Телефоны магазина');phones.innerHTML='<div class="shop-panel-head"><h2>Связаться с нами</h2><button data-shop-close aria-label="Закрыть телефоны">×</button></div><a href="tel:+79613011919"><b>+7 961 301-19-19</b><span>Позвонить ↗</span></a><a href="tel:+79613011818"><b>+7 961 301-18-18</b><span>Позвонить ↗</span></a><p>Пн–Пт · 09:00–18:00</p>';header.append(phones);
  let opened=null,owner=null;
  function positionPanel(){if(!opened)return;const gap=12,w=window.innerWidth,h=header.getBoundingClientRect();opened.style.maxWidth=(w-gap*2)+'px';opened.style.top=Math.max(0,h.bottom+6)+'px';opened.style.maxHeight=Math.max(100,innerHeight-h.bottom-18)+'px';const width=opened.getBoundingClientRect().width;const right=owner.getBoundingClientRect().right;opened.style.left=Math.max(gap,Math.min(opened===mega?(w-width)/2:right-width,w-width-gap))+'px';opened.style.right='auto';}
  window.addEventListener('resize',positionPanel);window.addEventListener('scroll',positionPanel,{passive:true});
  const close=(focus=false)=>{if(!opened)return;opened.hidden=true;owner.setAttribute('aria-expanded','false');document.body.classList.remove('shop-panel-open');const prev=owner;opened=null;owner=null;if(focus)prev.focus();};
  const toggle=(panel,button,keyboard=false)=>{const was=opened===panel;close();if(was)return;opened=panel;owner=button;panel.hidden=false;button.setAttribute('aria-expanded','true');document.body.classList.add('shop-panel-open');positionPanel();if(keyboard)panel.querySelector('a,button').focus();};
  for(const [button,panel] of [[catalog,mega],[more,info],[contact,phones]]){button.addEventListener('click',()=>toggle(panel,button));button.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();if(opened!==panel)toggle(panel,button,true);else panel.querySelector('a,button').focus();}});}
  header.addEventListener('click',e=>{if(e.target.closest('[data-shop-close]'))close(true);else if(e.target.closest('.shop-panel a,#cityBtn'))close();});
  document.addEventListener('click',e=>{if(!header.contains(e.target))close();});
  search.querySelector('input').addEventListener('focus',()=>close());
  document.addEventListener('keydown',e=>{if(!opened)return;if(e.key==='Escape'){e.preventDefault();close(true);}if(e.key==='Tab'){const all=[owner,...opened.querySelectorAll('a,button')].filter(e=>e.getClientRects().length),first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
  window.addEventListener('hashchange',()=>close());
  const size=()=>{const h=header.getBoundingClientRect().height;document.documentElement.style.setProperty('--header-clearance',(h+16)+'px');document.documentElement.style.setProperty('--shop-header-height',h+'px');};new ResizeObserver(size).observe(header);size();
  let frame=0;const scroll=()=>{frame=0;header.classList.toggle('is-scrolled',scrollY>80);};window.addEventListener('scroll',()=>{if(!frame)frame=requestAnimationFrame(scroll);},{passive:true});scroll();
  // Wholesale remains in the information menu and footer; account has its own route.
  document.querySelector('footer a[href="#/account"]')?.closest('li')?.remove();
  let mode='grid';try{if(localStorage.getItem('pt_catalog_view')==='list')mode='list';}catch{}
  function applyView(){const grid=document.querySelector('.catalog-results>.grid');if(grid){grid.classList.toggle('catalog-list',mode==='list');document.querySelectorAll('[data-catalog-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.catalogView===mode)));}}
  const previous=render;
  render=function(){
    const old=document.querySelector('#sideWrap'),keepOpen=old?.classList.contains('open')&&matchMedia('(max-width:767px)').matches,sideScroll=old?.scrollTop||0;
    previous();const side=document.querySelector('#sideWrap'),catalogEl=document.querySelector('.catalog');
    if(!catalogEl)return;
    const results=side.nextElementSibling;results.classList.add('catalog-results');
    const toolbar=results.querySelector('.toolbar'),sort=toolbar.querySelector('.sort'),select=document.createElement('select');select.className='catalog-sort';select.setAttribute('aria-label','Сортировка');
    select.innerHTML=[['pop','Сначала в наличии'],['hit','Подборка'],['asc','Сначала дешевле'],['desc','Сначала дороже']].map(([v,n])=>`<option value="${v}">${n}</option>`).join('');select.value=filters.sort;select.addEventListener('change',()=>{filters.sort=select.value;filters.page=1;render();});sort.replaceWith(select);
    const switcher=document.createElement('div');switcher.className='catalog-view';switcher.setAttribute('role','group');switcher.setAttribute('aria-label','Вид товаров');switcher.innerHTML=`<button type="button" data-catalog-view="grid" aria-label="Плитка" title="Плитка">${gridIcon}</button><button type="button" data-catalog-view="list" aria-label="Список" title="Список">${listIcon}</button>`;toolbar.append(switcher);
    const pager=results.querySelector('.pager');if(pager){pager.setAttribute('aria-label','Страницы каталога снизу');pager.setAttribute('role','navigation');pager.querySelectorAll('[data-page]').forEach(b=>{if(b.classList.contains('on'))b.setAttribute('aria-current','page');if(!b.getAttribute('aria-label'))b.setAttribute('aria-label','Страница '+b.dataset.page);});const top=pager.cloneNode(true);top.classList.add('pager-top');top.setAttribute('aria-label','Страницы каталога сверху');toolbar.after(top);}
    if(side){side.scrollTop=sideScroll;if(keepOpen){side.classList.add('open');document.body.classList.add('filter-sheet-lock');document.querySelector('#filtersToggle').setAttribute('aria-expanded','true');}side.querySelector('.filter-close').textContent='Показать товары';}
    applyView();
  };
  document.addEventListener('click',e=>{const button=e.target.closest('[data-catalog-view]');if(!button)return;mode=button.dataset.catalogView;try{localStorage.setItem('pt_catalog_view',mode);}catch{}applyView();});
  render();
})();
